version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - ./.env.dev
    volumes:
      - ./app/tmp/db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -rf ./app/tmp/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
